DrinkMessageList = [
    "Redbull",
    "Monster",
    "Coca Cola",
    "Fanta",
    "Orangina",
    "Sprite",
    "7Up",
    "Ice Tea",
    "Schweppes",
    "Gini",
    "Canada dry",
    "Champomy",
    "Mountain Dew",
    "Bière",
    "Despe",
    "Leffe",
    "Vodka",
    "Whisky",
    "Pastis",
    "Rhum",
    "Bourbon",
    "Vin",
    "Vin Blanc",
    "Vin Rouge",
    "Rosé",
    "Tequila",
    "Absinthe",
    "Martini",
    "Jägermeister",
    "Passoã",
    "Schnaps",
    "Malibu",
    "Mojito",
    "Sex on the Beach",
    "Blue Lagoon",
    "Sangria",
    "Anisette",
    "Breizh Cola",
    "Café",
    "Arizona",
    "Latte Macchiato",
    "Cappuccino"
]
